{% set name = "secure" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/secure-{{ version }}.tar.gz
  sha256: 942c10b8cfbde9e3a7961cf17833c9139d6e14ee39d23428230e4b8c8bc2de26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - secure
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/TypeError/secure
  doc_url: https://secure.readthedocs.io/en/latest/
  summary: A lightweight package that adds security headers for Python web frameworks.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
