{% set python_min = "3.10" %}
{% set name = "secure" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/secure-{{ version }}.tar.gz
  sha256: bb492b9ca2ae66d04f4718675a18de1d1a29217aaded3d6cb5bd8b4ba2e2a645

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
    - wheel
  run:
    - python >={{ python_min }}

test:
  imports:
    - secure
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/TypeError/secure
  doc_url: https://secure.readthedocs.io/en/latest/
  summary: A lightweight package that adds security headers for Python web frameworks.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
