{% set name = "secure" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/secure-{{ version }}.tar.gz
  sha256: f9bf274681bc22b8b37df0ee8985d9972ee96409899d60560d373aa39c43b23c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - secure
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/TypeError/secure
  doc_url: https://secure.readthedocs.io/en/latest/
  summary: A lightweight package that adds security headers for Python web frameworks.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
